In [2]:
!pip3 install torch 


In [3]:
import torch
from torch.nn import Linear
import torch.nn as nn
import matplotlib.pyplot as plt

In [4]:
print(torch.manual_seed(1)) #generates a random seed value for model 
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)


Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [5]:
x= torch.tensor([[2.0],[3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.randn(100,1)
y = x
# print(x)
# print(y)
plt.plot(20, 50, 'o')

In [1]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    def forward(self,x):
        pred = self.linear(x)
        return pred

NameError: name 'nn' is not defined

In [1]:
torch.manual_seed(1)
model = LR(1,1)
print(list(model.parameters()))
x= torch.tensor([[2.0],[3.3]])
print(model.forward(x))

NameError: name 'torch' is not defined